# Generated by Django 4.2.18 on 2025-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
